### ISSUE TITLE
Can you privide preprocessing h5py file？

### ISSUE THREAD

**Issue by amusi** [cai199626/PDNet#1]
Can you privide data_ecssd_224x224x2_T.h5 for me？
I already down the vgg161_merge_224x224x2_weight.0.168.hdf5.
I want to jump preprocess.py and train.py. 
I just want to test the result directly. 
So can you privide data_ecssd_224x224x2_T.h5 or other preprocessing h5py file for me？
thank you for your attention

**Comment by amusi** [comment]
作者没有回复我，所以没有拿到测试模型。cfj123456cfj是我微信，如果感兴趣可以加个好友

**Comment by wanglaotou** [comment]
Hi, I have already download the vgg161_merge_224x224x2_weight.0.168.hdf5 and vgg16_deep_fuse_512.0.129.hdf5, and I have modified the test.py to change the hdf5 path. But I get error like: "KeyError: "Unable to open object (object 'x' doesn't exist)"". 
And I cannot download the model in google drive, it seems that we don't have the permission.
Does someone have the same problem?

**Comment by 15721130626** [comment]
作者后来把测试模型放上去了，我是能跑通的，google drive的话，你翻墙下载了吗？我之前下载下来了

At 2018-12-20 09:32:20, "wanglaotou" <notifications@github.com> wrote:


Hi, I have already download the vgg161_merge_224x224x2_weight.0.168.hdf5 and vgg16_deep_fuse_512.0.129.hdf5, and I have modified the test.py to change the hdf5 path. But I get error like: "KeyError: "Unable to open object (object 'x' doesn't exist)"".
And I cannot download the model in google drive, it seems that we don't have the permission.
Does someone have the same problem?

**Comment by wanglaotou** [comment]
> 
> 作者后来把测试模型放上去了，我是能跑通的，google drive的话，你翻墙下载了吗？我之前下载下来了 At 2018-12-20 09:32:20, "wanglaotou" <notifications@github.com> wrote: Hi, I have already download the vgg161_merge_224x224x2_weight.0.168.hdf5 and vgg16_deep_fuse_512.0.129.hdf5, and I have modified the test.py to change the hdf5 path. But I get error like: "KeyError: "Unable to open object (object 'x' doesn't exist)"". And I cannot download the model in google drive, it seems that we don't have the permission. Does someone have the same problem? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我从作者提供的两个百度云下载下来了两个hdf5文件，分别是vgg161_merge_224x224x2_weight.0.168.hdf5 和vgg16_deep_fuse_512.0.129.hdf5，google drive帆樯后还需要权限，所以没法下载。你只用前两个也能跑通test.py吗？

**Comment by 15721130626** [comment]
我记得pdnet的代码里面有好几个网络，你看看是不是你网络调用错了，这个模型只对应其中的一个网络，而且好像还不是最终的那个网络，翻墙下载的那个才是最终模型

在 2018-12-20 15:04:37，"wanglaotou" <notifications@github.com> 写道：


作者后来把测试模型放上去了，我是能跑通的，google drive的话，你翻墙下载了吗？我之前下载下来了 At 2018-12-20 09:32:20, "wanglaotou" notifications@github.com wrote: Hi, I have already download the vgg161_merge_224x224x2_weight.0.168.hdf5 and vgg16_deep_fuse_512.0.129.hdf5, and I have modified the test.py to change the hdf5 path. But I get error like: "KeyError: "Unable to open object (object 'x' doesn't exist)"". And I cannot download the model in google drive, it seems that we don't have the permission. Does someone have the same problem? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我从作者提供的两个百度云下载下来了两个hdf5文件，分别是vgg161_merge_224x224x2_weight.0.168.hdf5 和vgg16_deep_fuse_512.0.129.hdf5，google drive帆樯后还需要权限，所以没法下载。你只用前两个也能跑通test.py吗？

**Comment by 15721130626** [comment]
我用的是deep_fuse那个模型，之前翻墙下的应该没错吧


| |
15721130626
研究生
|
|
上海大学
邮箱：15721130626@163.com
|

签名由 网易邮箱大师 定制

On 12/20/2018 19:49, 15721130626 wrote:
我记得pdnet的代码里面有好几个网络，你看看是不是你网络调用错了，这个模型只对应其中的一个网络，而且好像还不是最终的那个网络，翻墙下载的那个才是最终模型

在 2018-12-20 15:04:37，"wanglaotou" <notifications@github.com> 写道：


作者后来把测试模型放上去了，我是能跑通的，google drive的话，你翻墙下载了吗？我之前下载下来了 At 2018-12-20 09:32:20, "wanglaotou" notifications@github.com wrote: Hi, I have already download the vgg161_merge_224x224x2_weight.0.168.hdf5 and vgg16_deep_fuse_512.0.129.hdf5, and I have modified the test.py to change the hdf5 path. But I get error like: "KeyError: "Unable to open object (object 'x' doesn't exist)"". And I cannot download the model in google drive, it seems that we don't have the permission. Does someone have the same problem? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我从作者提供的两个百度云下载下来了两个hdf5文件，分别是vgg161_merge_224x224x2_weight.0.168.hdf5 和vgg16_deep_fuse_512.0.129.hdf5，google drive帆樯后还需要权限，所以没法下载。你只用前两个也能跑通test.py吗？

**Comment by 15721130626** [comment]
我用这个模型跑出来的前两个数据集和论文里的差不多，如果这个是最终模型，我就用这个模型，可以嘛


| |
15721130626
研究生
|
|
上海大学
邮箱：15721130626@163.com
|

签名由 网易邮箱大师 定制

On 12/22/2018 10:46, 15721130626 wrote:
我用的是deep_fuse那个模型，之前翻墙下的应该没错吧


| |
15721130626
研究生
|
|
上海大学
邮箱：15721130626@163.com
|

签名由 网易邮箱大师 定制

On 12/20/2018 19:49, 15721130626 wrote:
我记得pdnet的代码里面有好几个网络，你看看是不是你网络调用错了，这个模型只对应其中的一个网络，而且好像还不是最终的那个网络，翻墙下载的那个才是最终模型

在 2018-12-20 15:04:37，"wanglaotou" <notifications@github.com> 写道：


作者后来把测试模型放上去了，我是能跑通的，google drive的话，你翻墙下载了吗？我之前下载下来了 At 2018-12-20 09:32:20, "wanglaotou" notifications@github.com wrote: Hi, I have already download the vgg161_merge_224x224x2_weight.0.168.hdf5 and vgg16_deep_fuse_512.0.129.hdf5, and I have modified the test.py to change the hdf5 path. But I get error like: "KeyError: "Unable to open object (object 'x' doesn't exist)"". And I cannot download the model in google drive, it seems that we don't have the permission. Does someone have the same problem? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我从作者提供的两个百度云下载下来了两个hdf5文件，分别是vgg161_merge_224x224x2_weight.0.168.hdf5 和vgg16_deep_fuse_512.0.129.hdf5，google drive帆樯后还需要权限，所以没法下载。你只用前两个也能跑通test.py吗？

**Comment by wanglaotou** [comment]
你好，google drive现在好像下载不了的，可以方便把你能跑的代码和模型给我发一份吗？非常感谢。

**Comment by lalychen** [comment]
> 嗨，我已经下载了vgg161_merge_224x224x2_weight.0.168.hdf5和vgg16_deep_fuse_512.0.129.hdf5，我修改了test.py以更改hdf5路径。但我得到的错误如下：“KeyError：”无法打开对象（对象'x'不存在）“”。
> 我无法在谷歌驱动器中下载该模型，似乎我们没有这个权限。
> 有人有同样的问题吗？

请问你这个问题是怎么解决的呀？
